Do not restart apache while preparing letsencrypt acme challenge

diff --git a/bin/v-add-letsencrypt-domain b/bin/v-add-letsencrypt-domain
--- a/bin/v-add-letsencrypt-domain
+++ b/bin/v-add-letsencrypt-domain
@@ -179,8 +179,8 @@ for auth in $authz; do
             mkdir -p $acme_challenge
             echo "$token.$THUMB" > $acme_challenge/$token
             chown -R $user:$user $well_known
-            $BIN/v-restart-web
-            check_result $? "Web restart failed" >/dev/null
+            # $BIN/v-restart-web
+            # check_result $? "Web restart failed" >/dev/null
         fi
     fi
 
