IPV6 support

diff --git a/bin/v-add-domain b/bin/v-add-domain
--- a/bin/v-add-domain
+++ b/bin/v-add-domain
@@ -1,6 +1,6 @@
 #!/bin/bash
 # info: add web/dns/mail domain
-# options: USER DOMAIN [IP] [RESTART]
+# options: USER DOMAIN [IP] [IPV6] [RESTART]
 #
 # The function adds web/dns/mail domain to a server.
 
@@ -13,21 +13,30 @@
 user=$1
 domain=$2
 ip=$3
-restart="${4-yes}"
+ipv6=$4
+restart="${5-yes}"
 
 # Includes
 source $VESTA/func/main.sh
 source $VESTA/func/ip.sh
+source $VESTA/func/ipv6.sh
 source $VESTA/conf/vesta.conf
 
 
 #----------------------------------------------------------#
 #                    Verifications                         #
 #----------------------------------------------------------#
-check_args '2' "$#" 'USER DOMAIN [IP] [RESTART]'
+check_args '2' "$#" 'USER DOMAIN [IP] [IPV6] [RESTART]'
 validate_format 'user' 'domain'
-if [ ! -z "$ip" ] ; then
+if [ ! -z "$ip" ] && [ "$IPV4" == 'yes' ] ; then
     validate_format 'ip'
+else
+  ip=''
+fi
+if [ ! -z "$ipv6" ] && [ "$IPV6" == 'yes' ] ; then
+    validate_format 'ipv6'
+else
+  ipv6=''
 fi
 is_object_valid 'user' 'USER' "$user"
 is_object_unsuspended 'user' 'USER' "$user"
@@ -47,37 +56,43 @@ if [ -z "$ip" ]; then
     fi
 fi
 
-# Web domain
+if [ -z "$ipv6" ]; then
+    ipv6=$(get_user_ipv6 $user)
+    if [ -z "$ipv6" ]; then
+        echo "Error: no avaiable IPV6 address"
+        log_event "$E_NOTEXIST" "$EVENT"
+        exit $E_NOTEXIST
+    fi
+fi
+
+# Working on web domain
 if [ ! -z "$WEB_SYSTEM" ]; then
-    $BIN/v-add-web-domain $user $domain $ip 'no'
-    return_code=$?
+    $BIN/v-add-web-domain $user $domain $ip $ipv6 'no'
+    check_result $? "can't add web domain" >/dev/null
 fi
 
-# Proxy support
-if [ ! -z "$PROXY_SYSTEM" ] && [ "$return_code" -eq 0 ]; then
-    extentions="jpg,jpeg,gif,png,ico,svg,css,zip,tgz,gz,rar,bz2,doc,xls"
-    extentions="$extentions,exe,pdf,ppt,txt,odt,ods,odp,odf,tar,wav"
-    extentions="$extentions,bmp,rtf,js,mp3,avi,mpeg,flv,html,htm"
-    $BIN/v-add-web-domain-proxy $user $domain 'default' "$extentions" 'no'
+# Working on DNS domain
+if [ ! -z "$DNS_SYSTEM" ]; then
+    $BIN/v-add-dns-domain $user $domain $ip $ipv6 "" "" "" "" "" "" "" "" 'no'
+    check_result $? "can't add dns domain" >/dev/null
 fi
 
-# DNS domain
-if [ ! -z "$DNS_SYSTEM" ] && [ "$return_code" -eq 0 ]; then
-    $BIN/v-add-dns-domain $user $domain $ip 'no'
-    return_code=$?
-fi
-
-# Mail domain
-if [ ! -z "$MAIL_SYSTEM" ] && [ "$return_code" -eq 0 ]; then
+# Working on mail domain
+if [ ! -z "$MAIL_SYSTEM" ]; then
     $BIN/v-add-mail-domain $user $domain
-    return_code=$?
+    check_result $? "can't add mail domain" >/dev/null
 fi
 
-# Restart services
-if [ "$restart" != 'no' ] && [ "$return_code" -eq 0 ]; then
+# Restarting services
+if [ "$restart" != 'no' ]; then
     $BIN/v-restart-web
-    $BIN/v-restart-proxy
+    check_result $? "can't restart web" > /dev/null
+    if [ ! -z "$PROXY_SYSTEM" ]; then
+        $BIN/v-restart-proxy
+        check_result $? "can't restart proxy" > /dev/null
+    fi
     $BIN/v-restart-dns
+    check_result $? "can't restart dns" > /dev/null
 fi
 
 
@@ -85,4 +100,4 @@ fi
 #                       Vesta                              #
 #----------------------------------------------------------#
 
-exit $return_code
+exit
